stages:
  - test
  - build
  - deploy

project-iThink-unit-tests:
  image: python:3-bullseye
  stage: test
  script:
    - cd project_iThink
    - pip install -r requirements.txt
    - python -m pytest

lint-test:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 project-iThink

# ghi-lint-test:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - pip install flake8
#     - flake8 project-iThink

front-end-build-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: node:lts-bullseye
  needs:
    - project-iThink-unit-tests
    - lint-test
  script:
    - cd ghi
    - npm install
    - npm run build
  artifacts:
    paths:
      - ghi/build/
  variables:
    PUBLIC_URL: https://binary_bandits.gitlab.io/iThink
    REACT_APP_iThink:

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - front-end-build-job
  needs:
    - front-end-build-job
  script:
    - mv ghi/build public
  artifacts:
    paths: public
