volumes:
    mongo-data:
        external: true
services:
  fastapi:
    build:
      context: project_iThink
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./project_iThink:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGO_URL: mongodb://root:password@mongo
      DATABASE_NAME: db-name
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      WAIT_HOSTS: mongo:27017
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: ${REACT_APP_SAMPLE_SERVICE_API_HOST}
  mongo:
    image: mongo:4
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
